import type { Image } from '@/schemas/generated'

export const getVisualization = async (id: string): Promise<Image> => {
	const res = await fetch(`/api/image/${id}`)
	return res.json()
}

export const images: Array<Image> = [
	{
		id: 1,
		title: 'leftElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712678803/n_M_CLARO_elewacja_frontowa_lewa_ebf368c46b.webp',
		hash: 'n_M_CLARO_elewacja_frontowa_lewa_ebf368c46b',
		alt: 'leftElevation',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_frontowa_lewa_ebf368c46b.webp',
		mimetype: 'image/webp',
		imageType: 'VISUALIZATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 2,
		title: 'rightElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712678803/n_M_CLARO_elewacja_frontowa_prawa_4ec1a4c970.webp',
		hash: 'n_M_CLARO_elewacja_frontowa_prawa_4ec1a4c970',
		alt: 'rightElevation',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_frontowa_prawa_4ec1a4c970.webp',
		mimetype: 'image/webp',
		imageType: 'VISUALIZATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 3,
		title: 'rearElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712678803/n_M_CLARO_elewacja_tylna_lewa_f9b84111fb.webp',
		hash: 'n_M_CLARO_elewacja_tylna_lewa_f9b84111fb',
		alt: 'rearElevation',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_tylna_lewa_f9b84111fb.webp',
		mimetype: 'image/webp',
		imageType: 'VISUALIZATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 4,
		title: 'rightElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712678803/n_M_CLARO_elewacja_tylna_prawa_7790090327.webp',
		hash: 'n_M_CLARO_elewacja_tylna_prawa_7790090327',
		alt: 'rightElevation',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_tylna_prawa_7790090327.webp',
		mimetype: 'image/webp',
		imageType: 'VISUALIZATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 5,
		title: 'rightElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712678802/n_M_CLARO_elewacja_prawa_84330413ae.webp',
		hash: 'n_M_CLARO_elewacja_prawa_84330413ae',
		alt: 'rightElevation',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_prawa_84330413ae.webp',
		mimetype: 'image/webp',
		imageType: 'VISUALIZATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 6,
		title: 'frontElevation',
		alt: 'frontElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712676312/n_M_CLARO_elewacja_frontowa_616e365307.webp',
		hash: 'n_M_CLARO_elewacja_frontowa_616e365307',
		caption: 'frontElevation',
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_frontowa_616e365307.webp',
		mimetype: 'image/webp',
		imageType: 'ELEVATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 7,
		title: 'rearElevation',
		alt: 'rearElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712676312/n_M_CLARO_elewacja_tylna_2708952937.webp',
		hash: 'n_M_CLARO_elewacja_tylna_2708952937',
		caption: 'rearElevation',
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_tylna_2708952937.webp',
		mimetype: 'image/webp',
		imageType: 'ELEVATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 8,
		title: 'rightElevation',
		alt: 'rightElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712676312/n_M_CLARO_elewacja_boczna_prawa_2305870af4.webp',
		hash: 'n_M_CLARO_elewacja_boczna_prawa_2305870af4',
		caption: 'rightElevation',
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_boczna_prawa_2305870af4.webp',
		mimetype: 'image/webp',
		imageType: 'ELEVATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 9,
		title: 'leftElevation',
		alt: 'leftElevation',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712676312/n_M_CLARO_elewacja_boczna_lewa_f97efeeec4.webp',
		hash: 'n_M_CLARO_elewacja_boczna_lewa_f97efeeec4',
		caption: 'leftElevation',
		projectId: 1,
		homeTypeId: 1,
		filename: 'n_M_CLARO_elewacja_boczna_lewa_f97efeeec4.webp',
		mimetype: 'image/webp',
		imageType: 'ELEVATION',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 10,
		title: 'livingRoom',
		alt: 'livingRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770991/nomado_M_CLARO_domy_modulowe_salon_03_eb61898d50.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_salon_03_eb61898d50',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_salon_03_eb61898d50.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 11,
		title: 'livingRoom',
		alt: 'livingRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770991/nomado_M_CLARO_domy_modulowe_salon_01_deb31c5ad9.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_salon_01_deb31c5ad9',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_salon_01_deb31c5ad9.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 12,
		title: 'bedroom',
		alt: 'bedroom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770991/nomado_M_CLARO_domy_modulowe_sypialnia_01_a74356be58.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_sypialnia_01_a74356be58',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_sypialnia_01_a74356be58.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 13,
		title: 'showerRoom',
		alt: 'showerRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770992/nomado_M_CLARO_domy_modulowe_lazienka_01_c514a97999.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_lazienka_01_c514a97999',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_lazienka_01_c514a97999.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 14,
		title: 'showerRoom',
		alt: 'showerRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770991/nomado_M_CLARO_domy_modulowe_lazienka_02_45c71ae3b4.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_lazienka_02_45c71ae3b4',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_lazienka_02_45c71ae3b4.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 15,
		title: 'livingRoom',
		alt: 'livingRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770992/nomado_M_CLARO_domy_modulowe_salon_02_9b6177f63e.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_salon_02_9b6177f63e',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_salon_02_9b6177f63e.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 16,
		title: 'bedroom',
		alt: 'bedroom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712770993/nomado_M_CLARO_domy_modulowe_sypialnia_02_e100192459.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_sypialnia_02_e100192459',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_sypialnia_02_e100192459.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',

		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 17,
		title: 'showerRoom',
		alt: 'showerRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712772096/nomado_M_CLARO_domy_modulowe_czesc_dzienna_2_858b1624d4.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_czesc_dzienna_2_858b1624d4',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_czesc_dzienna_2_858b1624d4.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 18,
		title: 'livingRoom',
		alt: 'livingRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712773207/nomado_M_CLARO_domy_modulowe_sypialnia_03fb8d0e13.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_sypialnia_03fb8d0e13',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_sypialnia_03fb8d0e13.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 19,
		title: 'showerRoom',
		alt: 'showerRoom',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712773206/nomado_M_CLARO_domy_modulowe_lazienka_13edc9c337.webp',
		hash: 'nomado_M_CLARO_domy_modulowe_lazienka_13edc9c337',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'nomado_M_CLARO_domy_modulowe_lazienka_13edc9c337.webp',
		mimetype: 'image/webp',
		imageType: 'INTERIOR',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 20,
		title: 'groundFloorPlan',
		alt: 'groundFloorPlan',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712684540/first_floor_1_538d65688d.svg',
		hash: 'first_floor_1_538d65688d',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'first_floor_1_538d65688d.svg',
		mimetype: 'image/svg',
		imageType: 'FLOOR_PLAN',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 21,
		title: 'houseSectionPlan',
		alt: 'houseSectionPlan',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712685097/przekroj_51b8a4a906.svg',
		hash: 'przekroj_51b8a4a906',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'przekroj_51b8a4a906.svg',
		mimetype: 'image/svg',
		imageType: 'SECTION_PLAN',
		createdAt: new Date(),
		updatedAt: new Date()
	},
	{
		id: 22,
		title: 'localizationPlan',
		alt: 'localizationPlan',
		url: 'https://res.cloudinary.com/tomasz-sosi-ski/image/upload/v1712695312/ZT_claro_d30c520662.svg',
		hash: 'ZT_claro_d30c520662',
		caption: null,
		projectId: 1,
		homeTypeId: 1,
		filename: 'ZT_claro_d30c520662.svg',
		mimetype: 'image/svg',
		imageType: 'LOCALIZATION_PLAN',
		createdAt: new Date(),
		updatedAt: new Date()
	}
]
