import type { Sun, Moon } from 'lucide-svelte'

export { default as Icon } from './Icon.svelte'
export { default as Logo } from './Logo.svelte'
export { default as Sun } from './Sun.svelte'
export { default as Moon } from './Moon.svelte'
export { default as Mail } from './Mail.svelte'
export { default as Languages } from './Languages.svelte'
export { default as Facebook } from './Facebook.svelte'
export { default as Instagram } from './Instagram.svelte'
export { default as TwitterX } from './TwitterX.svelte'
export { default as Phone } from './Phone.svelte'
export { default as Flower } from './Flower.svelte'
export { default as Leaf } from './Leaf.svelte'
export { default as Sprout } from './Sprout.svelte'
export { default as Shrub } from './Shrub.svelte'
export { default as Trees } from './Trees.svelte'
export { default as Menu } from './Menu.svelte'
export { default as PanelRightOpen } from './PanelRightOpen.svelte'
export { default as MoreHorizontal } from './MoreHorizontal.svelte'
export { default as Globe } from './Globe.svelte'
export { default as Home } from './Home.svelte'
export { default as RotateCw } from './RotateCw.svelte'
export { default as User } from './User.svelte'
export { default as Trash2 } from './Trash2.svelte'
export { default as Pencil } from './Pencil.svelte'
export { default as PlusSquare } from './PlusSquare.svelte'
export { default as X } from './X.svelte'
export { default as Youtube } from './Youtube.svelte'
export { default as Burger } from './Burger.svelte'
export { default as Currency } from './Currency.svelte'
export { default as HeartHandshake } from './HeartHandshake.svelte'
export { default as LogoTitle } from './LogoTitle.svelte'

export type IconTYPE = {
	Sun: typeof Sun
	Moon: typeof Moon
}
